# Generated by Django 3.2 on 2024-07-17 16:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=50, validators=[users.models.validate_role]),
        ),
    ]
