# Generated by Django 3.2 on 2024-07-17 18:08

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.models.validate_username, django.core.validators.MinLengthValidator(limit_value=3), django.core.validators.RegexValidator(regex='^w\\\\Z')], verbose_name='username'),
        ),
    ]
