# Generated by Django 3.2 on 2024-07-18 16:21

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.models.validate_username, django.core.validators.MinLengthValidator(limit_value=5), django.core.validators.RegexValidator(regex='^[\\w.@+-]+\\Z')], verbose_name='username'),
        ),
    ]
