# Generated by Django 3.2 on 2024-07-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='rating',
            new_name='score',
        ),
    ]
