# Generated by Django 3.2 on 2024-07-24 13:04

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[api.validators.year_validator], verbose_name='Год выхода'),
        ),
    ]
