# Generated by Django 3.2 on 2024-07-21 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0005_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.titles', verbose_name='Произведение'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('author', 'title')},
        ),
    ]
